kubepack/lib-helm

Makefile, repo/registry.go
=> Don't cache authenticated chart repositories.

Makefile, action/install.go, action/list.go, action/uninstall.go, action/upgrade.go, action/util.go, go.mod, go.sum
=> Add helm actions

chart/lib.go, chart/lib_test.go
=> Handle error and remove \n in GetChangedValues

chart/lib.go, chart/lib_test.go, go.mod, go.sum, vendor/github.com/alessio/shellescape/.gitignore, vendor/github.com/alessio/shellescape/.travis.yml, vendor/github.com/alessio/shellescape/AUTHORS, vendor/github.com/alessio/shellescape/LICENSE, vendor/github.com/alessio/shellescape/README.md, vendor/github.com/alessio/shellescape/go.mod, vendor/github.com/alessio/shellescape/shellescape.go, vendor/modules.txt
=> Shell escape generated command

chart/lib.go
=> Simplify escapeKey

action/install.go
=> Fix install chart command

action/list.go
=> Pass namespace to ListOptions

repo/chartrepo.go
=> Add Load, ListCharts & ListVersions helper to ChartRepository

action/install.go, action/upgrade.go
Signed-off-by: Masudur Rahman <masud@appscode.com>
=> Use chart.Raw instead of chart.Files

repo/reponame.go
=> Add ListHelmHubRepositories

pkg/storage/driver/app_util.go, pkg/storage/driver/applications.go
=> Fix delete editor

pkg/repo/registry.go
=> Use UI_WIZARD_CHARTS_DIR env variable to load charts from local dir

pkg/chart/loader/fs.go, pkg/chart/loader/load.go, pkg/chart/loader/load_test.go, pkg/chart/loader/testdata/lib.go
=> Load chart from embedded filesystem

pkg/repo/registry.go, pkg/repo/registry_interface.go
=> Add EmbeddedRegistry

pkg/action/action.go, pkg/action/deploy.go, pkg/action/install.go, pkg/action/list.go, pkg/action/uninstall.go, pkg/action/upgrade.go
=> Allow passing log function

pkg/chart/lib.go
- don't repeat append cmds
- detect removed values
=> Fix GetChangedValues function

go.mod, go.sum, pkg/values/options.go, vendor/github.com/containerd/containerd/images/image.go, vendor/github.com/containerd/containerd/remotes/docker/fetcher.go, vendor/github.com/containerd/containerd/remotes/docker/resolver.go, vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go, vendor/github.com/containerd/containerd/version/version.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go, vendor/github.com/opencontainers/image-spec/specs-go/version.go, vendor/github.com/opencontainers/runc/libcontainer/user/user.go, vendor/modules.txt
=> Add ValuesBytes option

pkg/action/deploy.go, pkg/action/install.go
=> Make clientOnly configurable

pkg/action/util.go
- fill kind
- ignore form resources from refilling
=> Fix RefillMetadata

go.mod, go.sum, pkg/chart/lib.go, vendor/gomodules.xyz/encoding/LICENSE, vendor/gomodules.xyz/encoding/json/deepcopy.go, vendor/gomodules.xyz/encoding/json/filter.go, vendor/gomodules.xyz/encoding/json/json.go, vendor/gomodules.xyz/encoding/json/parser.go, vendor/modules.txt
=> Add GetValuesDiff and GetValuesDiffYAML

pkg/values/preset.go
=> Load preset correctly from cluster

.github/workflows/ci.yml, Makefile, pkg/chart/loader/directory.go, pkg/chart/loader/load_test.go, pkg/downloader/doc.go, pkg/getter/doc.go, pkg/getter/httpgetter.go, pkg/getter/httpgetter_test.go, pkg/internal/ignore/doc.go, pkg/internal/test/ensure/ensure.go, pkg/internal/test/test.go, pkg/internal/tlsutil/tls.go, pkg/repo/doc.go, pkg/repo/index.go, pkg/repo/repo.go, pkg/repo/reponame.go, pkg/repo/repotest/doc.go, pkg/repo/repotest/server.go, pkg/storage/driver/app_util.go, pkg/test/ensure/ensure.go, pkg/test/test.go
=> Use Go 1.19

pkg/action/deploy.go, pkg/action/install.go, pkg/action/template.go, pkg/action/upgrade.go
Signed-off-by: Masudur Rahman <masud@appscode.com>
=> Make Values field embedded type in helm options

pkg/repo/registry.go
=> Load HelmRepositories to track private ones

pkg/action/template.go
=> Support passing options for template renderer

pkg/action/action.go
=> Configure release name on kube client

pkg/repo/registry.go
Always allow bypassing appscode chart registries
=> Add --bypass-chart-registries flag

pkg/storage/driver/app_util.go
=> Remove app.kubernetes.io/managed-by key from app selector

pkg/repo/registry.go
- register only for HelmRepository
=> Register only for HelmRepository

pkg/repo/oci.go
Signed-off-by: Masudur Rahman <masud@appscode.com>
=> Fetch LegacyChart from repository url

pkg/repo/registry.go, pkg/repo/registry_interface.go
Signed-off-by: Masudur Rahman <masud@appscode.com>
=> Add GetHelmRepository method in IRegistry interface
